### ISSUE TITLE
body with direction : rtl

### ISSUE THREAD

**Issue by mahmoudZakaria90** [zeroxme/bootstrap-3-arabic#21]
sorry for the two issues,  i just want to ask about giving the body direction : rtl 
because when i did this before any jquery plugin i embed in my document like : gallery slider or simple bootstrap slider were destroyed 
how can i fix this ?

i tried before this line i've created :
_:not(body),_:not(div),*:not(html){ direction: rtl }
it works

**Comment by zeroxme** [comment]
your question is kind of irrelevant to the purpose of the repo but I don't advice using this line of code to be honest because it's too general. Also using the `*` has some performance issues.

The idea of converting any code to RTL is to change properties that affects the direction like floating, margins, paddings, clearing and etc... JS has nothing to do with directions unless if the JS code is direction dependent which means the CSS properties that affects directions are being manipulated inside the JS

**Comment by mahmoudZakaria90** [comment]
the line of code is too general ? ok what's wrong ?! 
i know the purpose of the repo and what you said about the purpose is so right but the body when it has that direction property also will cause a performance issues like js plugins and you are right about JS code direction dependent but don't you think this is must be considered as an issue also ?? and each time i embed a plugin of those with direction dependence must give it a direction :ltr

**Comment by mahmoudZakaria90** [comment]
for example :
-flex-slider
-owl-carousel 
-bx-slider
-pgwCarousel

**Comment by zeroxme** [comment]
I totally get your point. If this property would affect any plugin within bootstrap I would fix it but it's not, so it's irrelevant. You can add/fix what you want to suite your needs in your own custom code
